[build]
  publish = "build"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/client/:clientId/*"
  to = "/docs/clients/:clientId/:splat"
  status = 200

[[redirects]]
  from = "/client/:clientId"
  to = "/docs/clients/:clientId/"
  status = 200

# Redirect for GUID validation
[[redirects]]
  from = "/client/*"
  to = "/404"
  status = 404
  conditions = { path = "!/client/[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}" }

# Default redirect
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200