import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  docs: [
    {
      type: 'doc',
      id: 'intro',
      label: 'Giriş',
    },
    {
      type: 'category',
      label: 'Octo Desktop',
      items: [
        {
          type: 'autogenerated',
          dirName: 'octo-desktop',
        },
      ],
    },
    {
      type: 'category',
      label: 'Octo Web',
      items: [
        {
          type: 'autogenerated',
          dirName: 'octo-web',
        },
      ],
    },
    {
      type: 'category',
      label: 'Backup',
      items: [
        {
          type: 'autogenerated',
          dirName: 'backup',
        },
      ],
    },
  ],
};

export default sidebars;