import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // Octo Desktop documentation sidebar
  octoDesktopSidebar: [
    {
      type: 'category',
      label: 'Octo Desktop',
      items: [
        {type: 'autogenerated', dirName: 'octo-desktop'},
      ],
    },
  ],

  // Octo Web documentation sidebar
  octoWebSidebar: [
    {
      type: 'category',
      label: 'Octo Web',
      items: [
        {type: 'autogenerated', dirName: 'octo-web'},
      ],
    },
   'introduction',
  ],

  // Client documentation sidebar (for private docs like Octo Lab)
  clientSidebar: [
    {
      type: 'category',
      label: 'Geliştirici Dökümanları',
      items: [
        {type: 'autogenerated', dirName: 'clients'},
      ],
    },
  ],
};

export default sidebars;
